apiVersion: v1

kind: Service

# O objetivo deste Service é permitir que
# outros Pods encontrem a API utilizando
# DNS interno do Kubernetes.
#
# O frontend fará chamadas para:
#
# http://backend-service:3000
#
# Como configurado no nginx.
#
# Este serviço não será exposto para fora do cluster

metadata:
  # Nome utilizado pelo frontend
  name: backend-service

spec:

  # Apenas acesso interno
  type: ClusterIP

  # Procura Pods com esta label
  selector:
    app: backend
  
  ports:
    # Porta do Service
    - port: 3000
      # Porta utilizada pelo container
      targetPort: 3000
      
      protocol: TCP

