apiVersion: v1

kind: ConfigMap

# No configmap se armazena as configurações
# não sensíveis da aplicação

metadata:
  name: app-config

data:
  DB_HOST: db-service
  
  #porta padrão do postgres
  DB_PORT: "5432"

  # não mais DB_NAME por causa do nosso database no db.js
  POSTGRES_DB: tasksdb
  