apiVersion: v1

kind: Secret

# ao contrário do configmap aqui se armazena informações sensíveis
# No kubernetes esses valores ficam codificados em Base64

metadata:

  name: db-secret

# define um tipo de objeto chamado Secret
# indica que o conteúdo armazenado é composto por
# dados genéricos sem formato específico exigido
type: Opaque

# ao invés de data
# o kubernetes aceita direto assim sem precisar de conversões (ex: base64)
stringData:
  # Usuário e senha como pedido na atividade
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin